Fs = 1e9;          % samples per second
dt = 1/Fs;         % seconds per sample
T = 1e-6;          % bit width
L = 14*T;          % Length of signal, seconds
t = (0:dt:L)';     % time axis
A = 3.5;           % Amplitude

Fc0 = 10e6;        % bit 0 frequency, Hertz
Fc1 = 5e6;         % bit 1 frequency, Hertz

% String 'AB', ASCII: 0100001 0100010:
pkg load signal;
figfilename = './ASCIIbitSignal_AB.jpg';
y = A*sin(pi*Fc0*(t-0.0*T)).*rectpuls(t-0.5*T,T) ...
    + A*sin(pi*Fc1*(t-1.0*T)).*rectpuls(t-1.5*T,T) ...
    + A*sin(pi*Fc0*(t-2.0*T)).*rectpuls(t-2.5*T,T) ...
    + A*sin(pi*Fc0*(t-3.0*T)).*rectpuls(t-3.5*T,T) ...
    + A*sin(pi*Fc0*(t-4.0*T)).*rectpuls(t-4.5*T,T) ...
    + A*sin(pi*Fc0*(t-5.0*T)).*rectpuls(t-5.5*T,T) ...
    + A*sin(pi*Fc1*(t-6.0*T)).*rectpuls(t-6.5*T,T) ...
    ...
    + A*sin(pi*Fc0*(t-7.0*T)).*rectpuls(t-7.5*T,T) ...
    + A*sin(pi*Fc1*(t-8.0*T)).*rectpuls(t-8.5*T,T) ...
    + A*sin(pi*Fc0*(t-9.0*T)).*rectpuls(t-9.5*T,T) ...
    + A*sin(pi*Fc0*(t-10.0*T)).*rectpuls(t-10.5*T,T) ...
    + A*sin(pi*Fc0*(t-11.0*T)).*rectpuls(t-11.5*T,T) ...
    + A*sin(pi*Fc1*(t-12.0*T)).*rectpuls(t-12.5*T,T) ...
    + A*sin(pi*Fc0*(t-13.0*T)).*rectpuls(t-13.5*T,T) ...
    ...
;
% Plot of the signal:
fig = plot(t,y);
axis([-10^-6 15*10^-6 -4 4]);
xlabel('Time (seconds)');
ylabel('Amplitude (Volts)');
title('Signal Pulse for String AB (ASCII: 0100001 0100010)');
saveas(fig, figfilename);
exit;
